Added proto options
openwrt/luci pull request #4328
Opened 2020-08-03 13:31 UTC by valexi7

Added options to luci proto to match Pull request #13009

https://github.com/openwrt/packages/pull/13009

2020-08-03 14:07 UTC, feckert commented
Please squash the two commits and also add a valid commit header for example `luci-proto-modemmanger: add missing options`

2020-08-03 19:31 UTC, valexi7 commented
> Please squash the two commits and also add a valid commit header for example `luci-proto-modemmanger: add missing options`

Thanks, done.

2020-08-04 06:59 UTC, feckert commented
I probably didn't make myself clear.
You have now changed the heading from P/R.
The [commit](https://github.com/openwrt/luci/pull/4328/commits/8132d94b41f2d26e71fe6d4f3e3c9b3cdb12264f) heading is the same.
Can you please change that too?
The commit heading will appear in the repo and not the P/R heading.

We already have log translation. Could you use this [translation](https://github.com/openwrt/luci/blob/master/modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js#L165) please?

2020-09-02 13:40 UTC, feckert commented
And also please update your commit message.
We only need one *Signed-off-by*.
Also the commit message should be more meaningful what you have done in this commit.
In the LuCI it is usually sufficient if it is obvious that only the heading of the commit message is entered.
As you have already done. So you need only on *Signed-off-by*. Please have a look at the other commits in this reposotory

2021-02-06 06:22 UTC, nickberry17 requested changes

2021-02-06 06:22 UTC, nickberry17 commented on protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
> +		s.taboption('general', form.Value, 'signalrate', _('Signal refresh rate'));
Hey @valexi7 , can you change it to something like this?  You should validate the input where possible.

```
o = s.taboption('general', form.Value, 'signalrate', _('Signal refresh rate'), _('How often to get the signal strength metrics from the modem, in seconds.'));
o.datatype = "uinteger";
```

2021-02-06 06:22 UTC, nickberry17 commented on protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
> +
Please remove this blank line

2021-06-11 12:37 UTC, nickberry17 commented
ping @valexi7

2023-12-04 00:22 UTC, merged