[19.07] luci-app-opkg: flush menu cache after opkg actions
openwrt/luci pull request #4402
Opened 2020-08-30 12:33 UTC by zorun

This is a partial backport of dc57e4bc6c83d6c869c318256057e3636bfc5d66

Fixes: #4077

Signed-off-by: Baptiste Jonglez <git@bitsofnetworks.org>

2020-09-01 19:47 UTC, aparcar commented
I faced this multiple times, I'll give it a try

2020-09-02 22:03 UTC, zorun commented
@aparcar did you managed to test this?

I had tested it by installing luci-app-openvpn and it worked: the menu entry appeared after the installation (I just needed to change page)

Btw, this is considered a release blocker for 19.07.4.

2020-09-03 14:35 UTC, hnyman commented
Making it absolutely perfect in 19.07 would likely take too much time compared to the benefit. Even the improvement of immediate action after new package is great.

All in all, the whole OpenWrt with LuCI universe does not expect desktop-level seamlessness. A reboot required here and there is quite ok.

2020-09-03 16:43 UTC, zorun commented
> Making it absolutely perfect in 19.07 would likely take too much time compared to the benefit. Even the improvement of immediate action after new package is great.

Agreed that making it perfect is impossible, but backporting a fix for a regression should be fine.

> All in all, the whole OpenWrt with LuCI universe does not expect desktop-level seamlessness. A reboot required here and there is quite ok.
> 
> Ps.
> 
> > this is considered a release blocker for 19.07.4.
> 
> By whom? Quite minor issue in any case.

By me :)

> Quite minor issue in any case.

It's a usability issue that causes confusion.

> (as the issue has been present in all 19.07.x releases, I find it hard to believe that it would really be consider a show-stopper...)

No, it's a regression introduced in 19.07.3, see #4077 . I haven't checked which exact commit caused the regression, but that would probably be 94f504f17864fcdf3447fe40160c59a3e93bbbdf .

Regressions should be fixed, especially when it's easy to do.

2020-09-03 19:49 UTC, aparcar commented
But brackets around it and I'm fine with a merge :)

2020-09-03 20:16 UTC, aparcar requested changes

2020-09-03 20:16 UTC, aparcar commented on applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
> +							L.ui.menu.flushCache();
```suggestion
						if (L.ui.menu && L.ui.menu.flushCache) { L.ui.menu.flushCache(); }
```

2020-09-03 20:33 UTC, jow- commented
No brackets around single statement conditions please.

2020-09-03 20:47 UTC, aparcar commented
> No brackets around single statement conditions please.

I just tested and it works as expected, I wasn't ware of that JavaScript behaviour.

```javascript
if(false)
console.log("foo"); console.log("bar")
```

Only print `'bar`, therefore it's fine.

2020-09-03 20:47 UTC, aparcar commented on applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
> +							L.ui.menu.flushCache();
Nevermind

2020-09-03 21:00 UTC, zorun commented
Yeah, and let's not start adding style changes to backports... Why make this so complicated?

2020-09-03 21:03 UTC, merged

2020-09-03 21:37 UTC, zorun commented
Thanks for merging!

2022-12-10 05:54 UTC, IngwiePhoenix commented
Came here after installing a few LuCi apps and realizing that the menu did not refresh.

Is there a command-line method to manually refresh the menu cache?

```
root@FriendlyWrt:/etc/tvheadend# opkg info luci
Package: luci
Version: git-20.074.84698-ead5e81
Depends: libc, uhttpd, uhttpd-mod-ubus, luci-mod-admin-full, luci-theme-bootstrap, luci-app-firewall, luci-app-opkg, luci-proto-ppp, libiwinfo-lua, luci-proto-ipv6, rpcd-mod-rrdns
Status: install user installed
Section: luci
Architecture: all
Size: 1045
Filename: luci_git-20.074.84698-ead5e81_all.ipk
Description: Standard OpenWrt set including full admin with ppp support and the default Bootstrap theme
Installed-Time: 1665787481

root@FriendlyWrt:/etc/tvheadend# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.2'
DISTRIB_REVISION='r19803-9a599fee93'
DISTRIB_TARGET='rockchip/armv8'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_DESCRIPTION='OpenWrt 22.03.2 r19803-9a599fee93'
DISTRIB_TAINTS='busybox'
```

Thanks :)

2022-12-10 13:13 UTC, jow- commented
No CLI way since you have to trigger a flush of the session storage in your browser.