luci-mod-status: add support for add device to wifi black/whitelist
openwrt/luci pull request #4507
Opened 2020-10-09 23:03 UTC by Ansuel

Add support for one-click add device to wifi black/whitelist in the status page. If the black/whitelist feature is enabled a combobox is displayed with the disconnect option.
Device already added will display only the disconnect button.

Fixes: #3675

@jow-  Another easy UTOPIA task ahahha

The first commit is needed since  theme-material have a display bug that show all the combo box bigger than expected....
(is problematic with the new introduced combobox in the wifi row)
![Immagine 2020-10-10 010050](https://user-images.githubusercontent.com/20289090/95638241-31179a00-0a94-11eb-8af1-ce4d75e8d542.jpg)

Also is there a way to make the disconnect button display first?

2020-10-10 09:05 UTC, jow- requested changes
Excellent work, a couple of little remarks below :)

2020-10-10 09:05 UTC, jow- commented on modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js
> +									'addlist': 'btn cbi-button cbi-button-remove',
If you pass a `sort` option you can override the order of choices:

```javascript
...
'click': ...,
'sort': [ 'disconnect', 'addlist' ],
'classes': {
    ...
}
...
```

2020-10-10 11:55 UTC, Ansuel commented on modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js
> +					this.isDeviceAdded[macs[j]] = true;
bss.mac is all upperCase

2020-10-30 20:22 UTC, jow- commented
@Ansuel - can you rebase it on top of the merged WPS feature?

2020-10-30 20:24 UTC, Ansuel commented
Sure give me a sec

2020-10-30 20:52 UTC, Ansuel commented
@jow- done an extra check would be good to make sure I didn't screw up

2020-10-31 01:14 UTC, stangri commented
This comment may not be relevant for this specific change, but please consider using allow/deny-lists terminology. ;)

2020-10-31 05:31 UTC, castillofrancodamian commented
> This comment may not be relevant for this specific change, but please consider using allow/deny-lists terminology. ;)

But if it's called that way

2020-10-31 21:03 UTC, merged

2020-10-31 21:04 UTC, jow- commented
Merged, thanks!