Add Luci for Eoip packege
openwrt/luci pull request #4690
Opened 2020-12-25 11:59 UTC by bogdik

For https://github.com/openwrt/openwrt/pull/3721

2020-12-26 20:05 UTC, stangri commented
Hey, thanks for the contribution. There was a discussion if the new lua-based luci packages will be accepted or not (since the transition to the javascript-based WebUI), I hope @hnyman or @Ansuel  or @feckert will chime in on that.

There are still a few things which need to be fixed to improve chances that this will be merged:
1. Please add "luci-app-eoip: " prefix to the commit message.
2. Please squash all commits into one commit and force-push the changes.
3. Please sign the commit with your real name.

2020-12-28 21:07 UTC, hnyman commented
Reference to packages PR https://github.com/openwrt/packages/pull/14334

Regarding LuCI, 
* there should be just one commit
* the commit needs to be properly titled, and signed off by you
* .pot file is empty although you have created
* preferably the new packages should use javascript instead of lua. This is so small GUI package, that it should be easy to convert.

2021-01-26 13:19 UTC, bogdik commented
Done

2021-01-26 13:37 UTC, bogdik commented
On last add info for dybamic option

2021-01-28 00:54 UTC, bogdik commented
> * there should be just one commit
> * the commit needs to be properly titled, and signed off by you
> * .pot file is empty although you have created
> * preferably the new packages should use javascript instead of lua. This is so small GUI package, that it should be easy to convert.

Check please

2021-01-29 09:12 UTC, hnyman requested changes
Some small comments

2021-01-29 09:12 UTC, hnyman commented on applications/luci-app-eoip/Makefile
> +PKG_VERSION:=1.0.1
There is no need for versioning in the LuCI packages as there is automatic versioning based on commit dates.
You can remove the PKG_VERSION line.

2021-01-29 09:12 UTC, hnyman commented on applications/luci-app-eoip/htdocs/luci-static/resources/view/eoip/eoip.js
> +		v.datatype = "and(and(max(4094), integer),and(min(1), integer))";
"range" datatype would be much easier and more clear.
`range(1,4094)`

2021-01-29 09:12 UTC, hnyman commented on applications/luci-app-eoip/Makefile
> +
You might add the target-indenpendent line:
`LUCI_PKGARCH:=all`

2021-01-29 09:12 UTC, hnyman commented on applications/luci-app-eoip/Makefile
> +
You should add the license database line. Your copyright sets is as Apache 2

`PKG_LICENSE:=Apache-2.0`

2021-01-31 17:13 UTC, hnyman commented
I have one more comment:

I think that there are still invalid datatypes:   `"min(0), integer"` looks faulty, used in two places.
It should be `"and(min(0), integer)"`  or likely it could just be the unsigned integer type `"uinteger", if the only restriction is that it needs to be non-negative integer. that "uinteger" pretty much defined that by itself.

Have you tested the app?

2021-02-01 10:04 UTC, bogdik commented
> Have you tested the app?

Yes, tested fine

2021-02-01 15:35 UTC, bogdik commented
Compiled, tested, everything is fine, everything works

2021-02-01 16:02 UTC, merged