luci-app-attendedsysupgrade: use correct linter settings
openwrt/luci pull request #5321
Opened 2021-08-31 21:14 UTC by aparcar

The previous settings would use spaces which messed up things since LuCI
uses tabs everywhere.

Also removed a stray console.log

Signed-off-by: Paul Spooren <mail@aparcar.org>

2021-08-31 21:14 UTC, aparcar commented
@feckert thoughts?

2021-09-01 06:58 UTC, feckert commented
@aparcar :+1:
But as far as I know, LuCI (and I do it that way) doesn't use `"` it uses `'` for strings.
But it's up to you if you want to change that.
And the line https://github.com/openwrt/luci/pull/5321/files#diff-6f92da1ee8b945f03c89ae863115e3689eda060789bf3d66401a0f9acde32eb1R44 has also the wrong quotations.
Which linter do you use?

2021-09-01 09:35 UTC, aparcar commented
> But as far as I know, LuCI (and I do it that way) doesn't use " it uses ' for strings.

Reworked to use '

>  And the line https://github.com/openwrt/luci/pull/5321/files#diff-6f92da1ee8b945f03c89ae863115e3689eda060789bf3d66401a0f9acde32eb1R44 has also the wrong quotations.

I don't understand what's wrong with the line you mention, it's using " in a print, that seems fine?

> Which linter do you use?

js-beautify https://github.com/beautify-web/js-beautify but I don't really care

2021-09-01 09:42 UTC, feckert commented
This line has the wrong quotation its not a **``** this must be changed to `'`.
I would also change this line to 

`_('Could not reach API at %s. Please try again later.').format(response.url)`

but I have not tested it

2021-09-01 09:43 UTC, aparcar commented
So using these special ` quotes is like f-strings in python, you can directly paste variables in there. Is there a problem with that?

2021-09-01 09:46 UTC, feckert commented
I have seen that there are problems with updating the translation. 
`Updating applications/luci-app-attendedsysupgrade/po/templates/attendedsysupgrade.pot ... standard input:44: warning: unterminated string`

2021-09-01 09:47 UTC, aparcar commented
Okay seems like translations shouldn't use these, I'll fix that.

2021-09-02 07:45 UTC, aparcar commented
The translation strings should be fixed now.

2021-09-03 08:41 UTC, feckert requested changes
I am not a javascript expert, maybe @jow- can help us, but I don't know your pattern with the `${`.  Is this valid javascript? I haven't seen it in the LuCI yet.
I would suggest we should use the function `format` and always use these `'`. Then we are on the safe side. Otherwise we break the translation?

2021-09-03 08:41 UTC, feckert commented on applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
> +					var sysupgrade_url = `${server_url}/store/${res.bin_dir}/${image.name}`;
I was just about to merge and went back over the pullrequest and saw the wrong comma again. Sorry
I would suggest that we use `'` over all.
If you are building a string then I would always use the `format` function.

2021-09-03 08:41 UTC, feckert commented on applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
> +						`${res.version_number} ${res.version_code}`,
The same as above

2021-09-03 08:41 UTC, feckert commented on applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
> +			`${server_url}/api/v1/revision/${version}/${target}`
Also wrong high commas?

2021-09-04 00:12 UTC, aparcar commented
Please see more about the template strings here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2021-09-06 07:39 UTC, aparcar commented
I've updated the script slightly to work with the openwrt-2020 theme as well.

2021-09-06 08:44 UTC, merged