luci-app-wireguard: convert to JavaScript
openwrt/luci pull request #5323
Opened 2021-09-01 13:23 UTC by lvoegl

### luci-app-wireguard
- luci-app-wireguard has been rewritten in JavaScript in a similar style to the old wireguard status app
- `luci.wireguard` rpcd has been rewritten in lua and now also includes the qr code generation and data backend from the old lua status app
- moved `luci.wireguard` rpcd from luci-proto-wireguard into luci-app-wireguard

![app-status](https://user-images.githubusercontent.com/60816858/131671986-7c0e31ba-0371-496b-b96c-78aa78efefbd.png)

### luci-proto-wireguard
- moved the qr code generation from the app into proto-wireguard
- added dependency to luci-app-wireguard

![generate qr](https://user-images.githubusercontent.com/60816858/131672011-3149681c-af08-4bde-a439-17198d9428f4.png)
![qr code](https://user-images.githubusercontent.com/60816858/131672023-c131e9fb-c2eb-46ec-b84b-74339b856dd4.png)

2021-09-01 16:26 UTC, stangri commented
Thanks for this tremendous effort!

> ### luci-proto-wireguard
> * moved the qr code generation from the app into proto-wireguard

What was the reason for moving qr code generation from luci app into luci-proto-wireguard?

2021-09-01 18:10 UTC, jow- requested changes
Great work! Thanks a lot for your effort. I added a couple of minor remarks below.

2021-09-01 18:10 UTC, jow- commented on applications/luci-app-wireguard/htdocs/luci-static/resources/view/wireguard/status.js
> +function bytesToStr(bytes) {
This entire function can be replaced with `'%1024mB'.format(bytes)`

2021-09-01 18:10 UTC, jow- commented on applications/luci-app-wireguard/htdocs/luci-static/resources/view/wireguard/status.js
> +				return generatePeerOption(...option);
LuCI JS should stay at ES5 yet, can you replace the spread operator with function.apply? `generatePeerOption.apply(null, option)`

2021-09-01 18:10 UTC, jow- commented on applications/luci-app-wireguard/htdocs/luci-static/resources/view/wireguard/status.js
> +				'[data-section-id="' + ifaceName + '"]'
This and similar string concat expressions could be replaced with `nodes.querySelector('[data-section-id="%q"]'.format(ifaceName))` for slightly better readability.

2021-09-03 11:10 UTC, lvoegl commented
> Thanks for this tremendous effort!
> 
> > ### luci-proto-wireguard
> > 
> > * moved the qr code generation from the app into proto-wireguard
> 
> What was the reason for moving qr code generation from luci app into luci-proto-wireguard?

Thank you. When you add a new peer you can generate a qr code for it without having to go to the status first. Also I think it rather belongs to the configuration than the status

2021-09-03 13:11 UTC, systemcrash commented
Well, if this conversion takes precedence, ensure that it accounts for what should happen in https://github.com/openwrt/luci/pull/5319 (or merge that first and rebase)

2021-09-03 15:54 UTC, feckert commented
@systemcrash You are right, but the `wireguard.htm` file is completely repllaced by status.js.
I am more in favour of merging this pull request and then your fix.
I think you need to rebase your pullrequest once this one has been merged.

2021-09-07 12:58 UTC, feckert commented
I have tested this now. I noticed the following issue.

I just have the situation on my system that qrencode is not installed and  the button to generate the QR is still displayed but does not work.

Either we include qrencode package as a dependency to luci-app-wireguard.
Or we have to check whether qrencode is installed.

The easiest way is to add qrencode package as a dependency to luci-app-wireguard from my point of view.

2021-09-07 20:37 UTC, systemcrash commented
> Either we include qrencode package as a dependency to luci-app-wireguard.
> Or we have to check whether qrencode is installed.
> 
> The easiest way is to add qrencode package as a dependency to luci-app-wireguard from my point of view.

There is no easy way >:D

I would do both - there's always going to be someone or some other package one day that removes qrencode or breaks this, or pkg is missing from a repo or someone downloads only one pkg file etc etc. So both dep and check for qrencode is safe.

2021-09-10 13:21 UTC, lvoegl commented
I have now added a message that appears when trying to generate a qr code if qrencode is not installed.

Also with the latest commit the qr code carries more information as shown in the description in the image below

![qr option](https://user-images.githubusercontent.com/60816858/132859402-e2146312-2aca-4a22-9310-8689de2c067f.png)

2021-09-22 06:29 UTC, merged

2021-09-22 06:30 UTC, feckert commented
Thanks

After the merge, this function should be update.
https://github.com/openwrt/luci/pull/5323/files#diff-6763953b63f260140aa13661899e49e1b06283df44fb6be93df63d30446a8313R13-R31

There is already a pull request that has to be rebased.
https://github.com/openwrt/luci/pull/5319

Ping @systemcrash

2021-09-22 10:22 UTC, systemcrash commented
@lvoegl are the translation strings what the compiler system put into the po files? Or something you manually cooked up?

Because every single `ago` message string lacks the %d (which is partially what #5319 should fix).

2021-09-26 07:09 UTC, hnyman commented
@feckert  @lvoegl 

I think that this PR made a strange change to the dependencies, deviating from the usual LuCI practice.

We had here the normal LuCI way: GUI app being on top, pulling in the underlying support packages
luci-app-wireguard --> luci-proto-wireguard + wireguard-tools

Now we strangely have the protocol on top, pulling in the GUI app.  That sounds abnormal to me.
luci-proto-wireguard depends on the GUI app.
Is there any real reasoning for that? 
We still need both in practice, so why the change?

I would like to revert that change.

(I noticed this as I lost the wireguard in my build, as my recipe contains the normal top-level items, usually the luci-app-xxx)

2021-09-26 07:41 UTC, feckert commented
luci-app-wireguard was coverted to Javascript.
So it uses now the ubus rpc to print the status. Also the qr code
generation moved from app to proto. So the luci-app-wireguard and
luci-proto-wirguard uses now a ubus rpcd luci.wireguard. Each of them have
a dependency to luci.wireguard. I think we have to fix the dependency or
split luci.wireguard to work independent. I would prefer the dependency fix

Hannu Nyman ***@***.***> schrieb am So., 26. Sept. 2021,
09:09:

> @feckert <https://github.com/feckert> @lvoegl <https://github.com/lvoegl>
>
> I think that this PR made a strange change to the dependencies, deviating
> from the usual LuCI practice.
>
> We had here the normal LuCI way: GUI app being on top, pulling in the
> underlying support packages
> luci-app-wireguard --> luci-proto-wireguard + wireguard-tools
>
> Now we strangely have the protocol on top, pulling in the GUI app. That
> sounds abnormal to me.
> luci-proto-wireguard depends on the GUI app.
> Is there any real reasoning for that?
> We still need both in practice, so why the change?
>
> I would like to revert that change.
>
> (I noticed this as I lost the wireguard in my build, as my recipe contains
> the normal top-level items, usually the luci-app-xxx)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/luci/pull/5323#issuecomment-927247499>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEHBA4FBSV32AXYLBISTT3UD3BJRANCNFSM5DGPHCEA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>