SocatG:add package
openwrt/luci pull request #5687
Opened 2022-02-16 18:13 UTC by big-tooth

2022-02-18 09:04 UTC, feckert reviewed
- Please change the commit message to `luci-app-socat: add app`
- Also add a `Signed-off-by:` to your commit please have a look to the other commits
- Please add a new line in each file
- Use the socat https://github.com/openwrt/packages/blob/master/net/socat/Makefile backend from the packages feed

2022-02-18 11:15 UTC, big-tooth commented on applications/luci-app-socatg/LICENSE
> +MIT License
maybe,or not

2022-02-18 14:53 UTC, big-tooth commented on applications/luci-app-socatg/README.md
> +# luci-app-socatg
English is default version,now

2022-03-07 13:06 UTC, feckert requested changes
I am also in favour of not needing the readme, because there is no added value in using the socat backend from the package feed.

2022-03-07 13:06 UTC, feckert commented on applications/luci-app-socatg/root/etc/init.d/socatg
> +#!/bin/sh /etc/rc.common
If you integrate the new uci options into the socat package, then this should not be necessary.

https://github.com/openwrt/packages/blob/master/net/socat/files/socat.init

2022-03-07 13:06 UTC, feckert commented on applications/luci-app-socatg/root/etc/uci-defaults/luci-socatg
> +#!/bin/sh
If we use the socat backend from the package feed, then we do not need this, as it is reload/restart automatically by openwrt

2022-03-07 13:06 UTC, feckert commented on applications/luci-app-socatg/luasrc/controller/socatg.lua
> +module("luci.controller.socatg", package.seeall)
If you port this to javascript, then we need an ACL instead of this file.

2022-03-07 13:06 UTC, feckert commented on applications/luci-app-socatg/Makefile
> +# PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)
We do not need that

2022-03-07 13:06 UTC, feckert commented on applications/luci-app-socatg/Makefile
> +include $(INCLUDE_DIR)/package.mk
Please also replace the this lines with:

```
include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
```
Have a look at the other application Makefiles in the repository

2023-03-05 08:13 UTC, BKPepe commented
@big-tooth Would you mind taking a look at your pull request and addressing the review? If not, there is a possibility that your pull request will be closed due to inactivity.

2023-03-07 06:37 UTC, closed without merging