luci-mod-status,mod-network: Added fqdn-name to DHCPv4 lease table
openwrt/luci pull request #5710
Opened 2022-03-08 14:07 UTC by MaxSKash

(as in DHCPv6)

Signed-off-by: Max S Kash <asukms@ya.ru>

2022-03-18 11:44 UTC, feckert commented
Please stash the two commits to one or update the second wit a valid commit message.

2022-03-19 09:37 UTC, MaxSKash commented
@feckert done.

2022-03-24 10:06 UTC, feckert requested changes
I have tested it and it works so far. Please change the styling
![Screenshot_20220324_110740](https://user-images.githubusercontent.com/553091/159892938-af3e451d-2555-4d6b-9938-ec71f3ba8e39.png)

2022-03-24 10:06 UTC, feckert commented on modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
> +							name = hint ? hint.name : null,
Just one more small comment:
Either indent or `var` at the beginning and with `;` at the end

2022-03-24 10:06 UTC, feckert commented on modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
> +							host = null;
Same here

2022-03-24 10:06 UTC, feckert commented on modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/40_dhcp.js
> +				host = null;
Since you have done it this way here, I would suggest that you do the same for the other two notes.

2022-03-24 22:12 UTC, MaxSKash commented
@feckert done.

2022-03-28 07:53 UTC, feckert commented
Fixed indentation and so pushed directly https://github.com/openwrt/luci/commit/8a46648e5bfb4b8f4d2452c51b5181631d260b6f

Thanks

2022-03-28 07:53 UTC, closed without merging