luci-app-firewall: allow ipv6 setup
openwrt/luci pull request #6040
Opened 2022-10-19 10:04 UTC by ptpt52

Allow setup ipv6 for Port Forwards and NAT Rules

2022-10-19 10:05 UTC, ptpt52 commented
@jow-  ping

2022-10-19 10:27 UTC, jow- requested changes

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/tools/firewall.js
> +			if (!L.isObject(devices[dev].flags) || !Array.isArray(ip4addrs) || !Array.isArray(ip6addrs) || devices[dev].flags.loopback)
This should be 
```javascript
if (!L.isObject(devices[dev].flags) || (!Array.isArray(ip4addrs) && !Array.isArray(ip6addrs)) || devices[dev].flags.loopback)
```

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/tools/firewall.js
> +		o.datatype = 'ipaddr("nomask")';
This change must be protected by `L.hasSystemFeature('firewall4')`

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/tools/firewall.js
> +			for (var i = 0; i < ip6addrs.length; i++) {
The IPv6 address suggestions should only be added if `L.hasSystemFeature('firewall4')`

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js
> +			_('Only match incoming traffic from this IP or range.'), '', hosts);
This and similar datatype changes only if `L.hasSystemFeature('firewall4')`

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js
> +		o.datatype = 'neg(ipmask("true"))';
dito

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js
> +		o.datatype = 'neg(ipmask("true"))';
dito

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js
> -			_('Redirect matched incoming traffic to the specified internal host'), 'ipv4', hosts);
dito

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js
> +		o.datatype = 'ipmask';
dito

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
> +			_('Match forwarded traffic from this IP or range.'), '', hosts);
dito

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
> +		o.datatype = 'neg(ipmask("true"))';
dito

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
> +			_('Match forwarded traffic directed at the given IP address.'), '', hosts);
dito

2022-10-19 10:27 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
> +		o.datatype = 'neg(ipmask("true"))';
dito

2022-10-19 11:53 UTC, ptpt52 commented
update:
1. Allow setup ipv6 for Port Forwards and NAT Rules if firewall4 is used.
2. Add 'Restrict to address family' option for NAT Rules, if family is any/empty , assume it is ipv4. this allow setup NAT6 rules in web ui.

2022-10-19 13:02 UTC, jow- requested changes

2022-10-19 13:02 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
> +				value = 'ipv4'
This can be removed, if `value` is the empty string, we should add host hints for both IPv4 and IPv6.

2022-10-19 13:02 UTC, jow- commented on applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
> +		o = s.taboption('general', form.ListValue, 'family', _('Restrict to address family'));
We should guard the entire `family` option declaration for SNATs:

```javascript
if (fw4) {
    o = s.taboption('general', form.ListValue, 'family', _('Restrict to address family'));
    ...
}
```

2022-10-19 13:51 UTC, ptpt52 commented
updated

@jow-  how to validate the datetype in the validate() function?
I want to check src_ip and dst_ip input the same family value.

2022-10-19 14:23 UTC, jow- commented
Hmm, you can query the valid state of the input fields to see if a valid IP address is present to begin with, then simply check that either both src and dest addrs contain colons or both do not contain colons. Something like that:

```javascript
o.validate = function(section_id, value) {
    fwtool.updateHostHints(this.map, section_id, 'src_ip', value, hosts);
    fwtool.updateHostHints(this.map, section_id, 'dest_ip', value, hosts);
    
    var sopt = this.section.getOption('src_ip'),
        dopt = this.section.getOption('dest_ip');

    if (!sopt.isValid(section_id) || !dopt.isValid(section_id) ||
        return true; // stop validating here, the other field will show an error already

    var sip = sopt.formvalue(section_id) || '',
        dip = dopt.formvalue(section_id) || '',
        sv6 = sip.indexOf(':') != -1),
        dv6 = dip.indexOf(':') != -1);

    if (!sip || !dip)
        return true; // if either or both are empty then fine

    if (sv6 ^ dv6)
        return _('Address family of source and destination IPs must match');    
};
```

However I would not do this validation in the `family` dropdown option but in both the `src_ip` and `dest_ip` ones. (Also do not forget about `rewrite_ip`, that one must match the address family as well). Best is to make a shared validator function for src_ip, dest_ip and rewrite_ip, then assign it to all three options.

2022-10-20 00:37 UTC, ptpt52 commented
update:
luci-app-firewall: snats: validate address family

2022-10-20 01:12 UTC, ptpt52 commented
there may be some bug on firewall backend,
I am trying setup this SNAT rule:
```
config nat 'nat6'
	option name 'nat6'
	option src 'wan'
	option target 'MASQUERADE'
	list proto 'all'
```
expecting `MASQ` for ipv4 and ipv6, but only ipv4 was set:
```
nft list table inet fw4 | grep nat6
meta nfproto ipv4 masquerade comment "!fw4: nat6"
```

2022-10-20 21:55 UTC, jow- commented
Yes, for backwards compatibility with fw3, only fw4 is assumed if no explicit `option family '*'` or `option family any` or `option family all` is given.

2022-10-25 02:11 UTC, ptpt52 commented
ready to merge?

2022-11-14 20:18 UTC, ptpt52 commented
is there any one others review on this? to make it get merged, maybe ping @feckert

2023-01-12 16:58 UTC, efahl commented
I tested the new changes in https://github.com/openwrt/luci/commit/9ca915ebc943fc7f248bc0100e061d547a189142 forwards.js and it worked for me.

2023-01-21 20:18 UTC, hnyman commented
@jow- 
You initially reviewed this a few months ago (and you are the firewall expert). 
Ready to merge?

2023-03-15 22:48 UTC, jow- commented
Sorry for the long delay, I managed to runtime test this only now. Merged via 9c55500fe8efa309d55f34c21d5ae2bf69fabf06 - thank your for your work @ptpt52 !

2023-03-15 22:49 UTC, closed without merging