luci-app-apfree-wifidog: add luci-app-apfree-wifidog
openwrt/luci pull request #6412
Opened 2023-06-03 01:53 UTC by liudf0716

add luci-app-apfree-wifidog for apfree-wifidog
https://github.com/openwrt/packages/pull/21203

2023-06-15 07:23 UTC, feckert requested changes
Everything else looks good.

2023-06-15 07:23 UTC, feckert commented on applications/luci-app-apfree-wifidog/htdocs/luci-static/resources/view/wifidogx.js
> +});
Could your please replace the comments `// <option nam>` with an empty line. This is not needed. And could you also move the description into an new line so we do not hit the 80 char line boundary.

2023-06-15 07:23 UTC, feckert commented on applications/luci-app-apfree-wifidog/htdocs/luci-static/resources/view/wifidogx.js
> +		// add client settings
Please remove this line

2023-06-15 07:23 UTC, feckert commented on applications/luci-app-apfree-wifidog/htdocs/luci-static/resources/view/wifidogx.js
> +		// add kcptun-client status section and option
Please remove this line

2023-06-17 07:09 UTC, liudf0716 commented on applications/luci-app-apfree-wifidog/htdocs/luci-static/resources/view/wifidogx.js
> +		// add kcptun-client status section and option
@feckert fixed, thanks!

2023-06-26 01:29 UTC, liudf0716 commented
@feckert What else can I do to get my pull request approved?

2023-12-04 03:01 UTC, systemcrash requested changes

2023-12-04 09:27 UTC, liudf0716 commented on applications/luci-app-apfree-wifidog/htdocs/luci-static/resources/view/wifidogx.js
> +			_('Wired client will be passed without authentication'));
@systemcrash yes.  a wired client does not require authentication to access the network.

2023-12-04 21:34 UTC, systemcrash approved these changes

2023-12-06 01:42 UTC, liudf0716 commented
@systemcrash @feckert 
What other actions should I take? I noticed the "work needed" label on the pull request. thanks

2023-12-30 23:40 UTC, systemcrash commented
> @systemcrash @feckert What other actions should I take? I noticed the "work needed" label on the pull request. thanks

Change that string and we can merge

2023-12-31 02:53 UTC, liudf0716 commented
> > @systemcrash @feckert What other actions should I take? I noticed the "work needed" label on the pull request. thanks
> 
> Change that string and we can merge

I'm sorry, I'm not sure which specific string you're referring to. Could you please provide more context or identify the exact string you'd like me to change? I was under the impression that I had already made all the necessary changes, but I'm happy to double-check and make any further adjustments.

2024-01-08 13:59 UTC, systemcrash commented
> I'm sorry, I'm not sure which specific string you're referring to. Could you please provide more context or identify the exact string you'd like me to change? I was under the impression that I had already made all the necessary changes, but I'm happy to double-check and make any further adjustments.

Look through this PR again, and resolve the outstanding review.

2024-01-24 00:50 UTC, closed without merging