luci-app-opkg: add warning about modifying packages
openwrt/luci pull request #6932
Opened 2024-02-19 19:30 UTC by dannil

A proposal for a fix for #6413 

It is a well-known fact that opkg doesn't check ABI-compatibility between dependencies and upgrading packages in a stable release is therefore not recommended. In addition, installing and removing packages blindly may result in rendering the device inaccessible as well, so caution should be taken when doing this.

This commit adds a warning which should help notify especially new users about these behaviors with a link to the wiki which advises to not upgrade packages.

See https://openwrt.org/meta/infobox/upgrade_packages_warning for more info, which is the same link that is used in the second paragraph.

Tested on Chrome and Firefox, both desktop and mobile (Android). All CSS used is theme-compatible and should therefore look at least decent across different themes.

![Screenshot_44](https://github.com/openwrt/luci/assets/7290072/9b8e0e9f-e996-40f4-87e4-8ad36e7c2f0b)

![Screenshot_45](https://github.com/openwrt/luci/assets/7290072/4a66dca7-5973-4ff0-b244-e3aa58a81446)

<details>
  <summary>First iteration of design, not relevant anymore</summary>

BootstrapLight:
![Screenshot_39](https://github.com/openwrt/luci/assets/7290072/a14fe02b-1d8a-4b3f-ae17-69aa3db4ded6)

BootstrapDark:
![Screenshot_40](https://github.com/openwrt/luci/assets/7290072/710b82eb-f8eb-49c1-9b03-1a956cca65cb)

Material:
![Screenshot_41](https://github.com/openwrt/luci/assets/7290072/765de4f6-a298-4362-ac3b-ba02bb58f6be)

OpenWrt2020:
![Screenshot_42](https://github.com/openwrt/luci/assets/7290072/934cd549-bc50-4637-be8d-251ab8ca1584)
</summary>

2024-02-21 19:15 UTC, systemcrash commented
Not optimal if it causes a pop-up or a button that must be clicked away.

2024-02-21 20:06 UTC, dannil commented
> Luci has UI notification API that can be used like:
> 
> ```
>  ui.addNotification(null, E('p', 'Werning!'), 'error');
> ```
> 
> Maybe you can use it instead?

Having a pop-up show up every time you navigate to the updates tab will most likely be very annoying to the user.

2024-02-21 20:56 UTC, jow- commented
Please also add warning banners that *installing* packages and *removing* packages can cause soft bricks or break access to the ui.

2024-02-21 22:21 UTC, systemcrash commented
Shall we add more banners and warnings that using openwrt will also
potentially soft brick their devices? 😉


Please also add warning banners that *installing* packages and *removing*
> packages can cause soft bricks or break access to the ui.
>

2024-02-21 22:23 UTC, dannil commented
I've updated the PR title, commit message, and screenshots to reflect the suggestion by @jow-

2024-03-12 20:35 UTC, dannil commented
@stokito @systemcrash @jow- is there any other changes we want or does it make sense to start thinking of merging it?

2024-03-12 21:27 UTC, stokito requested changes

2024-03-12 21:27 UTC, stokito commented on applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
> +				E('p', _('See <a %s">explanation on wiki</a> why especially upgrading should be avoided.').format(
Replace `<a %s">` with `<a %s>`

2024-03-12 21:35 UTC, systemcrash commented
Is it possible to reduce the warning text to a concise nugget? That page is now exploding with lines, colours and text and this does not make it easier to handle.  How about:
```
Warning! Package operations can break your system.')),
				E('p', _('Read <a %s>this</a>.').format(
```

2024-03-12 21:38 UTC, dannil commented
> Is it possible to reduce the warning text to a concise nugget? That page is now exploding with lines, colours and text and this does not make it easier to handle. How about:
> 
> ```
> Warning! Package operations can break your system.')),
> 				E('p', _('Read <a %s>this</a>.').format(
> ```

Absolutely, I like that idea.

2024-03-12 22:25 UTC, stokito approved these changes

2024-03-12 22:54 UTC, systemcrash commented
And now... to acknowledge this big warning dialogue. 

@yurtpage suggested

> Luci has UI notification API that can be used like:
> 
> ```
>  ui.addNotification(null, E('p', 'Werning!'), 'error');
> ```
> 
> Maybe you can use it instead?

But maybe something more resilient. Like an 'acknowledge' button, that when clicked, stores a boolean flag in the config that determines whether the warning is shown at page load. We've done our diligence, the user can hide the warning. 

What do you think @dannil ?

2024-03-13 06:41 UTC, dannil commented
> And now... to acknowledge this big warning dialogue.
> 
> @yurtpage suggested
> 
> > Luci has UI notification API that can be used like:
> > ```
> >  ui.addNotification(null, E('p', 'Werning!'), 'error');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe you can use it instead?
> 
> But maybe something more resilient. Like an 'acknowledge' button, that when clicked, stores a boolean flag in the config that determines whether the warning is shown at page load. We've done our diligence, the user can hide the warning.
> 
> What do you think @dannil ?

Yes, I've actually thought about that too. I think we could do something akin to how the "Confirm" button behaves in warning dialogs (such as when you don't have a password set on your root user), here's an example from nftables:

![Screenshot_43](https://github.com/openwrt/luci/assets/7290072/0d21abe3-285d-4f30-b220-e3ec48aa6e9f)

Do we think it would be necessary to have a checkbox somewhere else (like under the "Configure opkg..." dialog) that would enable users to show the warning again? I personally think it shouldn't be needed.

2024-03-13 09:17 UTC, stangri commented
1. I believe a nicer way would be: `Warning: package operations can break your system (more information).` and link the wiki article from `more information`?
2. If not, is it possible to move the `Read this` text to the line before and avoid the line break?

2024-03-14 21:07 UTC, stokito commented
Honestly I think it would be better to make same introduction paragraph as other pages have:

![luci-app-opkg](https://github.com/openwrt/luci/assets/415502/4c96a1c9-0889-43ef-953a-5daec8cc5a59)


```html
<div class="cbi-map-descr">
Install additional software and upgrade existing packages with opkg.. 
<br><b>Warning!</b> Package operations <a href="href="https://openwrt.org/meta/infobox/upgrade_packages_warning" target="_blank" rel="noreferrer">can break your system</a>
</div>
```

I.e. the warning can be just a sentence in the introduction.

We may add more important notes e.g. about feeds and disk space usage.
Given that this UI messages are more likely to be translated than a Wiki page it will improve cautious of users. That's why we need to add at least a few words that ABI may broken and that core modules shouldn't be updated at all. Yes, wiki explains this better but who reads it?

BTW the article in Wiki is in inbox e.g. in "draft" state. On the wiki itself not so much of information about package management https://openwrt.org/docs/guide-user/additional-software/start

2024-03-14 23:49 UTC, systemcrash commented
> Honestly I think it would be better to make same introduction paragraph as other pages have:


Also good. Less intrusive yet ever present.

2024-03-15 00:06 UTC, dannil commented
> Honestly I think it would be better to make same introduction paragraph as other pages have:
> 
> ![luci-app-opkg](https://private-user-images.githubusercontent.com/415502/312993790-4c96a1c9-0889-43ef-953a-5daec8cc5a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjEyMDksIm5iZiI6MTcxMDQ2MDkwOSwicGF0aCI6Ii80MTU1MDIvMzEyOTkzNzkwLTRjOTZhMWM5LTA4ODktNDNlZi05NTNhLTVkYWVjOGNjNWE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwMDAxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmQ5YWM5MzgxM2E3ZDRjOTZkYTljZjdjNTA4MTk5ZWQwNTYzMmEzMTQ1MjQ4NDBiM2JiZjNkZjAwMjkwNzcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TEgPvTFvwfopbpsc0r1mU3JXCOj-ril3_gZj1ZY4Gm0)
> 
> ```
> <div class="cbi-map-descr">
> Install additional software and upgrade existing packages with opkg.. 
> <br><b>Warning!</b> Package operations <a href="href="https://openwrt.org/meta/infobox/upgrade_packages_warning" target="_blank" rel="noreferrer">can break your system</a>
> </div>
> ```
> 
> I.e. the warning can be just a sentence in the introduction.
> 
> We may add more important notes e.g. about feeds and disk space usage. Given that this UI messages are more likely to be translated than a Wiki page it will improve cautious of users. That's why we need to add at least a few words that ABI may broken and that core modules shouldn't be updated at all. Yes, wiki explains this better but who reads it?
> 
> BTW the article in Wiki is in inbox e.g. in "draft" state. On the wiki itself not so much of information about package management https://openwrt.org/docs/guide-user/additional-software/start

I like this as well, especially the less intrusive part. Also, I've had trouble to implement a UCI config for opkg (since the package itself doesn't define this I need to do some hacky solution with creating the file from the LuCI app, which I don't like) which can entirely be avoided with the above suggestion. 

I'll implement this solution in the following days since it's both much less intrusive and way easier technically to implement since we don't need the while "Hide" logic.

2024-03-16 05:53 UTC, stokito approved these changes

2024-03-16 11:45 UTC, merged

2024-03-16 11:45 UTC, systemcrash commented
Merged. Thanks @dannil !