luci-app-hysteria: add luci-app-hysteria
openwrt/luci pull request #7221
Opened 2024-07-31 06:37 UTC by findlayfeng

- [ ] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [ ] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [ ] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [ ] Tested on: (architecture, openwrt version, browser) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#24701 in sister repo
- [ ] Description: (describe the changes proposed in this PR)

2024-07-31 09:22 UTC, hnyman commented
File example.pot is wrongly named. should be hysteria.pot

2024-08-01 18:30 UTC, systemcrash commented on applications/luci-app-hysteria/htdocs/luci-static/resources/view/hysteria/client.js
> +			_('Directory where the Hysteria Client configuration file are located.')
file is
files are

2024-08-01 18:30 UTC, systemcrash commented on applications/luci-app-hysteria/htdocs/luci-static/resources/view/hysteria/client.js
> +			_('A feature-packed proxy & relay tool optimized for lossy'));
for lossy what?

2024-08-01 18:30 UTC, systemcrash commented on applications/luci-app-hysteria/htdocs/luci-static/resources/view/hysteria/client.js
> +			_('Nft Tabel Set')
Table

2024-08-01 18:30 UTC, systemcrash commented on applications/luci-app-hysteria/htdocs/luci-static/resources/view/hysteria/client.js
> +			_('Nft Tabel Set')
Nft => NFT

2024-08-01 18:31 UTC, systemcrash commented on applications/luci-app-hysteria/htdocs/luci-static/resources/view/hysteria/server.js
> +			_('A feature-packed proxy & relay tool optimized for lossy'));
for lossy what?

2024-08-01 18:31 UTC, systemcrash commented on applications/luci-app-hysteria/htdocs/luci-static/resources/view/hysteria/server.js
> +			_('Directory where the Hysteria Server configuration file are located.')
file is
files are

2024-08-01 18:32 UTC, systemcrash requested changes
mostly spelling/grammar

2024-08-02 06:22 UTC, findlayfeng commented
@systemcrash Thank you for your review, the revision has been completed

2024-08-02 12:07 UTC, systemcrash approved these changes

2024-10-20 22:37 UTC, closed without merging