luci-proto-modemmanager: add initial EPS bearer support
openwrt/luci pull request #7331
Opened 2024-10-17 20:27 UTC by robimarko

- [ ] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [ ] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [ ] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [ ] Tested on: (architecture, openwrt version, browser) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [ ] Description: (describe the changes proposed in this PR)

ModemManager protocol has supported setting initial EPS bearer since package commit [1], so lets expose the same support via LuCI as well.

[1] https://github.com/openwrt/packages/commit/af12147f8c54ac3a44d32c5c1bd95099bc9a6c74

2024-10-17 22:49 UTC, systemcrash requested changes
Need to unburden i18n people. Shorter strings and put `<br/>` outside of them.

2024-10-17 22:49 UTC, systemcrash commented on protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
> +		custom: Use different options when establishing a connection (these options are prefixed with an 'init_')."));
```js
		_('none: Do not set an initial EPS bearer (default behaviour)') + '<br/>' +
		_('default: Use the configuration options above (APN, IP Type, ...).') + '<br/>' +
		_('custom: Use different options when establishing a connection (these options are prefixed with %s).').format('<code>init_</code>'));
```

2024-10-19 09:23 UTC, robimarko commented on protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
> +		custom: Use different options when establishing a connection (these options are prefixed with an 'init_')."));
Done

2024-10-19 11:00 UTC, systemcrash approved these changes

2024-10-19 11:04 UTC, systemcrash commented
@feckert any comments?

2024-10-21 06:26 UTC, merged

2024-10-21 06:26 UTC, feckert commented
Thanks merged!