Add Info_dashboard package
openwrt/luci pull request #7424
Opened 2024-11-25 11:00 UTC by tp82d1

This package (`luci-app-tplink_dashboard`) introduces a dashboard interface for OpenWrt, inspired by the user interface of TP-Link firmware. The primary goal is to simulate the visual and functional aspects of TP-Link dashboards within the OpenWrt ecosystem.

#### **Features**

-   **TP-Link-Inspired Design**: A minimalist and visually appealing design that mirrors the layout and simplicity of TP-Link firmware dashboards.
-   **Dynamic Icons**: Includes interactive icons for Internet connection, device detail and connected devices.
    -   **Internet Status**: Displays the current connection status dynamically.
    -   **Device Detail**: Displays information about the router.

    -   **DHCP Monitoring**: Displays the number of active DHCP clients in real time.

#### **Testing**

The package was tested under the following conditions:

-   **OpenWrt Versions**:
    -   23.05.0

#### **Screenshots**
<img width="1084" alt="InternetStatus_NotConnected" src="https://github.com/user-attachments/assets/2f95686d-f737-491a-8532-992b4f5f1ff1">
<img width="1084" alt="dashboard" src="https://github.com/user-attachments/assets/75d8f3bf-c954-4fd2-b014-3b7561b1f3b6">
<img width="1084" alt="InternetStatus_connected" src="https://github.com/user-attachments/assets/c787b1ef-88c9-4313-bca2-ec16063fff24">
<img width="1035" alt="DeviceInfo" src="https://github.com/user-attachments/assets/93ee5eac-907d-420b-83e6-99f8edb73736">
<img width="1084" alt="DHCP" src="https://github.com/user-attachments/assets/950def8b-e771-4800-95f0-b83b7bfdc9be">

2024-11-25 16:45 UTC, systemcrash commented
Of course have written permission from them to use them, right?

2024-11-25 17:22 UTC, stangri commented
First of all, I want to say it's a tremendous work to have a skin written for luci. If/when the IP/copyright issues of the assets and the name in the package title are resolved, I have the following comments on this PR:
1. you're including both the `applications/luci-mod-tplink_dashboard` and `luci-mod-tplink_dashboard` directories in your PR. I'm guessing it's an oversight and you only need one of them.
2. the proper location for modules (luci-mod-*) is actually `modules`, so I believe it should be `modules/luci-mod-tplink_dashboard`.
3. The iptables is not a default package for 23.05, 24.10 nor snapshots and you declare exec access to iptables/ip6tables binaries. I believe the mod should support nft natively before the PR is merged.

2024-11-25 17:44 UTC, systemcrash commented
> Thanks for your replies, ill try my best to solve what you have mentioned in your replies. if I couldn't push them in same branch, i'll close and reopen new one :).

Please don't - figure out how to use git. That's what it's designed for.

2024-11-25 17:51 UTC, systemcrash commented
Go grab some royalty-free vector graphics to replace the assets here. And credit/attribute any author involved.

2024-11-25 18:22 UTC, stangri commented
> Go grab some royalty-free vector graphics to replace the assets here. And credit/attribute any author involved.

It's worth checking if TP-Link may have published those assets with the GPL code. 

Including their brand name in the name of the package might infringe on their copyright tho.

2024-11-28 20:28 UTC, systemcrash commented
Looks considerably better. 
- can you replace the ❌ and ✅ with SVG versions?
- fix the test formalities, commit messages.

2024-11-28 21:03 UTC, dannil requested changes

2024-11-28 21:03 UTC, dannil commented on modules/luci-mod-info_dashboard/root/usr/share/luci/menu.d/luci-mod-tplink_dashboard.json
This file needs to be renamed to match `luci-mod-info_dashboard`.

2024-11-28 21:03 UTC, dannil commented on modules/luci-mod-info_dashboard/root/usr/share/rpcd/acl.d/luci-mod-tplink_dashboard.json
This file needs to be renamed to match `luci-mod-info_dashboard`.

2024-11-29 11:30 UTC, closed without merging