luci-mod-rdash: add new package
openwrt/luci pull request #7431
Opened 2024-11-29 13:11 UTC by tp82d1

### Description
This PR adds a new package, `luci-mod-rdash`, which provides an interactive dashboard for routers.

Key features:
- Dynamic icons for internet status, device information and connected clients.
- Real-time system information display, including CPU usage and connected devices number.

2024-11-29 19:39 UTC, Ansuel commented
screenshot of this?

2024-11-29 19:46 UTC, systemcrash commented
@Ansuel 

See previous attempt at #7424

> screenshot of this?

2024-11-30 14:02 UTC, systemcrash commented on modules/luci-mod-info-dashboard/Makefile
> +PKG_RELEASE:=1
Please drop these. git semantic versioning works fine.

2024-11-30 14:03 UTC, systemcrash commented on modules/luci-mod-info-dashboard/htdocs/luci-static/resources/view/info-dashboard/css/custom.css
> +.dashboard-container{display:flex;justify-content:center;align-items:center;margin:35px 0}.icon{width:100px;height:auto;cursor:pointer;transition:transform .3s;padding-bottom:.7em}.icon:hover{opacity
Please don't do this. It shall be readable by reviewers. Let the compilers optimise it for install.

2024-11-30 14:05 UTC, systemcrash commented on modules/luci-mod-info-dashboard/htdocs/luci-static/resources/view/info-dashboard/include/d_dhcp.js
> +'use strict';'require baseclass';'require rpc';'require uci';'require network';'require validation';var callLuciDHCPLeases=rpc.declare({object:'luci-rpc',method:'getDHCPLeases',expect:{'':{}}});retur
don't do this. use multiple lines

2024-11-30 14:05 UTC, systemcrash commented on modules/luci-mod-info-dashboard/htdocs/luci-static/resources/view/info-dashboard/index.js
> +'use strict';'require view';'require dom';'require network';'require rpc';document.querySelector('head').appendChild(E('link',{'rel':'stylesheet','type':'text/css','href':L.resource('view/info-dashbo
don't do this

2024-11-30 14:07 UTC, systemcrash commented
Consider naming your dashboard something creative. Name it after yourself if you want. "info" is waaaaay too generic and may clash with namespaces eventually that shall be used by openwrt itself.

2024-11-30 18:09 UTC, systemcrash commented on modules/luci-mod-rdash/htdocs/luci-static/resources/view/rdash/index.js
> +}
extra line at end here plz

2024-11-30 18:09 UTC, systemcrash commented on modules/luci-mod-rdash/htdocs/luci-static/resources/view/rdash/include/d_devices.js
> +});
extra line at end here plz

2024-11-30 18:10 UTC, systemcrash commented on modules/luci-mod-rdash/htdocs/luci-static/resources/view/rdash/css/custom.css
> +}
extra line at end here plz

2024-11-30 18:12 UTC, systemcrash commented
squash commits please

2024-11-30 21:06 UTC, systemcrash commented
Revise your commit message to simply "introduce new luci-mod-rdash dashboard" or something so people don't go looking for any "changes".

Any comments from @dannil or @stangri or @stokito ?

2024-11-30 21:09 UTC, systemcrash commented
One question: how does everything look in dark mode? Those black line diagrams on a dark background might look interesting. :)

2024-11-30 21:17 UTC, dannil requested changes

2024-11-30 21:17 UTC, dannil commented on modules/luci-mod-rdash/htdocs/luci-static/resources/view/rdash/include/d_dhcp.js
This file is using tab indentation instead of space as the rest of your JS files, you may want to change that.

2024-11-30 21:21 UTC, systemcrash commented on modules/luci-mod-rdash/htdocs/luci-static/resources/view/rdash/include/d_dhcp.js
Well spotted. Yes please, use tab indentation.

2024-11-30 22:50 UTC, systemcrash commented
> One question: how does everything look in dark mode? Those black line diagrams on a dark background might look interesting. :)

Take a look at how I did it in dfd802abdcd98100d509a6c84014f6854584b8b9 (if your css does not already handle that).

2024-12-01 09:06 UTC, hnyman commented
If this gets merged, I hope that you're committing to maintain this in compatible status for several years. 

(We have been burned with enthusiastic creation of some theme or dashboard, and then soon after that the creator loses interest, and the app starts rotting when there are changes in the surrounding OpenWrt. )

2024-12-04 14:07 UTC, jow- commented on modules/luci-mod-rdash/root/usr/share/rpcd/acl.d/luci-mod-rdash.json
> +				"file": [ "exec" ]
This exec permissions does not appear to be required, please drop it.

2024-12-04 14:08 UTC, jow- commented on modules/luci-mod-rdash/root/usr/share/rpcd/acl.d/luci-mod-rdash.json
> +				"network.rrdns": [ "lookup" ]
There does not appear to be any reverse lookup calls in this code, so please drop this permission.

2024-12-04 14:09 UTC, jow- commented on modules/luci-mod-rdash/root/usr/share/rpcd/acl.d/luci-mod-rdash.json
> +				"/proc/sys/net/netfilter/nf_conntrack_max": [ "read" ]
The simplified dashboard code does not appear to read any of those files, drop the read permissions for them.

2024-12-04 14:11 UTC, jow- commented on modules/luci-mod-rdash/root/usr/share/rpcd/acl.d/luci-mod-rdash.json
> +				"luci": [ "getVersion" ],
This appears unused

2024-12-31 14:36 UTC, systemcrash commented
@tp82d1 Please address the comments. It's not that scary to maintain the app. If you don't, it simply gets removed. Not a big deal. Give it a try.

2025-01-13 19:00 UTC, closed without merging